### ISSUE TITLE
Report event type in request data for Task events

### ISSUE THREAD

**Issue by Neppers** [vliolios/event-poster-plugin#3]
PullRequest events send through `action` property, but Task events don't.

You can still decipher what is happening, but as everything goes to the same endpoint it'd be much easier to lookup a consistent property. For example, Jira webhooks always send `webHookEvent` which looks something like `jira:issue_created`, `jira:issue_updated`

Could even emulate their structure for the sake of consistency:

- `bitbucket:task_created`
- `bitbucket:pullrequest_approved`
- etc.

**Comment by vliolios** [comment]
Yes, currently there is no event data transformation except for a few exclusions from the serialisation to avoid issues caused by circular references.

It's easy to add an action property to the Task events before posting them. I'll try and put that in before the first release

**Comment by vliolios** [comment]
Fixed in v1.0.0
